version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - '3306:3306'
  app:
    build:
      target: prod
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: example
      DATABASE_PASSWORD: example
      DATABASE_NAME: example
    ports:
      - '3000:3000'
      - '9229:9229'
    depends_on:
      - db
